#!/usr/bin/env python

import os
import re
import sys

VERSION_TYPES   = ['MAJOR', 'MINOR', 'BUGFX', 'TRIVL']
VERSION_RE_STR  = r"#define VERSION_%s ([\d]*)"

def get_version():
  "Returns a string of the version from main.c"
  # Try to find the src dir.  This method simply recurses up the directory tree
  # looking for a 'src' dir
  main_found = False
  start_dir = os.getcwd()
  for i in range(0, 5):
    src_dir = os.path.join(start_dir, '../'*i, 'src')
    if os.path.isdir(src_dir):
      # Found a src dir, does it have main.c?
      main_file = os.path.join(src_dir, 'main.c')
      if os.path.isfile(main_file):
        main_found = True
        break
  
  if main_found:
    file_main = open(main_file)
    str_main = file_main.read()
    version = []
    for v in VERSION_TYPES:
      r = re.compile(VERSION_RE_STR % v)
      m = r.findall(str_main)
      if m:
        version.append(m[0])
    return '.'.join(version)
  
if __name__ == "__main__":
  print get_version()